<a href="https://colab.research.google.com/github/being-snehil/supreme-dollop/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4]

In [ ]:
type(a)

list

In [ ]:
 a_np = np.array(a)

In [ ]:
type(a_np)

numpy.ndarray

In [ ]:
a_np*2

array([2, 4, 6, 8])

In [ ]:
li = range(1000)

In [ ]:
li

range(0, 1000)

In [ ]:
z = np.arange(1,5)
z

array([1, 2, 3, 4])

In [ ]:
np.resize(z,(2,9))

array([[1, 2, 3, 4, 1, 2, 3, 4, 1],
       [2, 3, 4, 1, 2, 3, 4, 1, 2]])

In [ ]:
z

array([1, 2, 3, 4])

In [ ]:
z.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
z

array([1, 2, 3, 4])

In [ ]:
z.reshape(1,4).ndim

2